version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lacoste-156-dev"
s3_bucket = "sftpgw-i-06e8a0b5d0a44b1fb"
s3_prefix = "users/Lacoste/"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["LacosteProductFunction=601772211076.dkr.ecr.us-east-1.amazonaws.com/lacoste-registry"]
disable_rollback = true